name: quizzzy
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.9
  pdf_text: ^0.5.0
  file_picker: ^4.5.0
  cloud_firestore: ^3.1.10
  ################################## Change when PR merged
  fdottedline:
    git:
      url: https://github.com/Karthick47v2/fdottedline.git
      ref: img-fix
  firebase_auth: ^3.3.9
  firebase_core: ^1.13.1
  firebase_messaging: ^11.2.15
  flutter_local_notifications: ^9.4.1
  firebase_dynamic_links: ^4.2.2
  http: ^0.13.4
  firebase_analytics: ^9.1.6
  cloud_functions: ^3.2.13
  firebase_analytics_web: ^0.4.0+11
  shared_preferences: ^2.0.13
  hive: ^2.1.0
  hive_flutter: ^1.1.0

dev_dependencies:
  hive_generator: ^1.1.2
  build_runner: ^2.1.10
  flutter_test:
    sdk: flutter
  mockito: ^5.1.0
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
  fonts:
    - family: Heebo
      fonts:
        - asset: assets/fonts/Heebo-Black.ttf
          weight: 900
        - asset: assets/fonts/Heebo-Bold.ttf
          weight: 700
        - asset: assets/fonts/Heebo-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Heebo-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Heebo-Light.ttf
          weight: 300
        - asset: assets/fonts/Heebo-Medium.ttf
          weight: 500
        - asset: assets/fonts/Heebo-Regular.ttf
          weight: 400
        - asset: assets/fonts/Heebo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Heebo-Thin.ttf
          weight: 100
