name: Python test

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    name: CI workflow
    strategy:
      matrix:
        python-version: ["3.8"]
    steps:
      - name: Checkout source repo
        uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Decode base64 secrets
        run: echo $SERVICE_ACCOUNT_SECRET | base64 -d > docker/app/secret/mock-key.json
        env:
          SERVICE_ACCOUNT_SECRET: ${{ secrets.SERVICE_ACCOUNT_SECRET }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint pytest pytest-cov spacy gdown
          pip install -r docker/app/requirements.txt
          python3 -m spacy download en_core_web_sm
      - name: Analysing the code with pylint
        run: |
          pylint $(git ls-files '*.py')
      - name: Test with pytest
        run: |
          python -m pytest --cov=./ --cov-report=xml
      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@v2
        with:
          env_vars: OS,PYTHON
          fail_ci_if_error: false
          flags: unittests
          verbose: true
